package main

import (
	"context"
	"fmt"
	"io"
	"os"
	"sync"

	"github.com/0neSe7en/sshfwd/internal/resolver"
)

const sshBinary = "ssh"

type command int

const (
	commandTunnel command = iota
	commandExport
)

func main() {
	if err := run(context.Background(), os.Args[1:], os.Stdout, os.Stderr); err != nil {
		if exitError, ok := err.(interface{ ExitCode() int }); ok {
			code := exitError.ExitCode()
			if code > 0 {
				os.Exit(code)
			}
		}
		fmt.Fprintln(os.Stderr, "sshfwd:", err)
		os.Exit(1)
	}
}

func run(ctx context.Context, args []string, stdout, stderr io.Writer) error {
	cmd, host, help, err := parseArgs(args)
	if err != nil {
		return err
	}
	if help {
		printUsage(stdout)
		return nil
	}

	path, err := configPath()
	if err != nil {
		return err
	}
	config, err := loadConfig(path)
	if err != nil {
		return fmt.Errorf("load %s: %w", path, err)
	}
	hostConfig, ok := config.Hosts[host]
	if !ok {
		return fmt.Errorf("host %q is not configured", host)
	}
	serviceResolver, err := resolver.New(config.Resolvers[hostConfig.Resolver], sshBinary)
	if err != nil {
		return fmt.Errorf("host %q: %w", host, err)
	}

	listeners, err := effectiveListeners(ctx, sshBinary, host)
	if err != nil {
		return err
	}
	if err := checkConflicts(hostConfig.Forwards, listeners); err != nil {
		return err
	}

	forwards, err := resolveForwards(ctx, serviceResolver, host, hostConfig.Forwards)
	if err != nil {
		return err
	}

	if cmd == commandExport {
		printExport(stdout, host, forwards)
		return nil
	}

	printResolved(stderr, forwards)
	return runTunnel(ctx, sshBinary, host, forwards)
}

func parseArgs(args []string) (command, string, bool, error) {
	if len(args) == 1 && (args[0] == "-h" || args[0] == "--help") {
		return commandTunnel, "", true, nil
	}
	if len(args) == 1 {
		return commandTunnel, args[0], false, nil
	}
	if len(args) == 2 && args[0] == "export" {
		return commandExport, args[1], false, nil
	}
	return commandTunnel, "", false, fmt.Errorf("usage: sshfwd <host> | sshfwd export <host>")
}

func resolveForwards(ctx context.Context, serviceResolver resolver.Resolver, host string, configs []ForwardConfig) ([]ResolvedForward, error) {
	forwards := make([]ResolvedForward, len(configs))
	errs := make([]error, len(configs))

	var wait sync.WaitGroup
	for i, config := range configs {
		wait.Add(1)
		go func() {
			defer wait.Done()
			endpoint, err := serviceResolver.Resolve(ctx, host, config.Service)
			if err != nil {
				errs[i] = err
				return
			}
			forwards[i] = ResolvedForward{
				ForwardConfig: config,
				Endpoint:      endpoint,
			}
		}()
	}

	wait.Wait()
	for _, err := range errs {
		if err != nil {
			return nil, err
		}
	}
	return forwards, nil
}

func printResolved(writer io.Writer, forwards []ResolvedForward) {
	for _, forward := range forwards {
		if forward.Endpoint.Node != "" {
			fmt.Fprintf(writer, "%s: %s -> %s (node %s)\n", forward.Service, forward.Local, forward.remoteAddress(), forward.Endpoint.Node)
		} else {
			fmt.Fprintf(writer, "%s: %s -> %s\n", forward.Service, forward.Local, forward.remoteAddress())
		}
	}
}

func printExport(writer io.Writer, host string, forwards []ResolvedForward) {
	fmt.Fprintln(writer, "# Generated by sshfwd; Consul endpoints are a point-in-time snapshot.")
	fmt.Fprintf(writer, "Host %s\n", host)
	for _, forward := range forwards {
		fmt.Fprintf(writer, "    LocalForward %s %s\n", forward.Local, forward.remoteAddress())
	}
}

func printUsage(writer io.Writer) {
	fmt.Fprintln(writer, `Usage:
  sshfwd <host>
  sshfwd export <host>`)
}
